import type { GadgetModel } from "gadget-server";

// This file describes the schema for the "shopifyShop" model, go to https://ynmadmin.gadget.app/edit to view/edit your model in Gadget
// For more information on how to update this file http://docs.gadget.dev

export const schema: GadgetModel = {
  type: "gadget/model-schema/v1",
  storageKey: "DataModel-Shopify-Shop",
  fields: {
    handle: {
      type: "string",
      storageKey: "NzXhS-Eij1hk::ufbocaQla-ye",
    },
    shopifySmartCollects: {
      type: "hasMany",
      children: {
        model: "shopifySmartCollect",
        belongsToField: "shop",
      },
      storageKey:
        "ModelField-vxaV1TIoDeuh::FieldStorageEpoch-c-kcZgGkA_Ct",
    },
  },
  shopify: {
    fields: [
      "address1",
      "address2",
      "appInstallations",
      "balanceTransactions",
      "bulkOperations",
      "checkoutApiSupported",
      "checkoutLineItems",
      "checkouts",
      "city",
      "collections",
      "collects",
      "company",
      "cookieConsentLevel",
      "country",
      "countryCode",
      "countryName",
      "countyTaxes",
      "currency",
      "customerAccountsV2",
      "customerEmail",
      "discountCodes",
      "discounts",
      "disputeEvidences",
      "disputes",
      "domain",
      "domains",
      "eligibleForCardReaderGiveaway",
      "eligibleForPayments",
      "email",
      "enabledPresentmentCurrencies",
      "finances",
      "forceSsl",
      "fulfillmentLineItems",
      "fulfillmentOrderLineItems",
      "fulfillmentOrders",
      "fulfillmentServices",
      "fulfillments",
      "gdprRequests",
      "googleAppsDomain",
      "googleAppsLoginEnabled",
      "hasDiscounts",
      "hasGiftCards",
      "hasStorefront",
      "ianaTimezone",
      "latitude",
      "longitude",
      "marketRegions",
      "marketWebPresences",
      "marketingSmsContentEnabledAtCheckout",
      "markets",
      "moneyFormat",
      "moneyInEmailsFormat",
      "moneyWithCurrencyFormat",
      "moneyWithCurrencyInEmailsFormat",
      "multiLocationEnabled",
      "myshopifyDomain",
      "name",
      "orderAdjustments",
      "orderLineItems",
      "orders",
      "passwordEnabled",
      "payouts",
      "phone",
      "planDisplayName",
      "planName",
      "preLaunchEnabled",
      "priceRules",
      "primaryLocale",
      "products",
      "province",
      "provinceCode",
      "refundDuties",
      "refundLineItems",
      "refunds",
      "requiresExtraPaymentsAgreement",
      "scriptTags",
      "setupRequired",
      "shippingLines",
      "shopOwner",
      "shopifyCreatedAt",
      "shopifyUpdatedAt",
      "source",
      "syncs",
      "taxShipping",
      "taxesIncluded",
      "tenderTransactions",
      "timezone",
      "transactionalSmsDisabled",
      "weightUnit",
      "zipCode",
    ],
  },
};
